update-notifications: true
bstats: true

tick-delay-between-joins: 4

prefix: "&2&lFake Players&7 Â»&r"

bungeecord:
  enabled: false
  ip: "127.0.0.1"
  fakeplayers-port: 5721
  bungeecord-fakeplayers-port: 5723

messages:
  no-permissions: "&cYou do not have permissions to execute that command."
  summon:
    failed: "Failed to summon a Fake Player."
    incorrect-number: "Cannot summon this amount of players."
    success-one: "Successfully summoned a Fake Player."
    trying-amount: "Trying to summon %arg2% Fake Players."
  chat:
    not-a-fake-player: "This is not a Fake Player!"
    player-is-not-online: "This player does not exist!"
  disband:
    failed: "This player does not exist or is not a Fake Player!"
    all-disbanded-success: "Successfully disbanded all Fake Players."
    one-disbanded-success: "Successfully disbanded %arg1%."
  action:
    invalid-player: "This Fake Player does not exist!"
    action-success: "Action has been successfully added to the player."
    actions-clear: "Actions have been successfully cleared."
  macro:
    invalid-player: "This Fake Player does not exist!"
    invalid-macro: "This macro could not be loaded."
    macro-doesnt-exist: "This macro does not exist."
    macro-perform: "Making '%arg2%' perform macro '%arg3%'"
    macro-successful-save: "Successfully saved macro '%arg3%' to file"
    macro-failed-save: "Failed to save macro '%arg3%' to file"
    macro-successful-load: "Successfully loaded macro '%arg3%' from file"
    macro-failed-load: "Failed to load macro '%arg3%' from file"
    incorrect-number: "Cannot execute macro this amount of times."
  reload: "Config has been successfully reloaded."